language: go
go:
- 1.10.x
sudo: false
script:
- make bootstrap test
before_deploy:
- make dist VERSION=${TRAVIS_TAG}
deploy:
  provider: releases
  api_key:
    secure: RCxosL/2HFgB2fiM7bjt3lNKsolnHYG7aylHCKzUl2wplPXrqip4W+6OI39S5WrCkR9LcPpF2asJDXbze+ggw3crJin03jpIRABFmhJiE2L1ykZSL1B+QC/AfgNXb3cD6HIKx3E2NoRFlS3r6iRzIjYCPVKKDksPh4MGnDCa99cE2s0YCfaZVZiMsd55zlaw86AxKr65t0QySHj64LaqwVxz6PuEqIT5PEouhXRapLC5FJT5A05p6D5mAWS8drPRdYwGVicmx6O1pMFEb76lvLOxMLdza3LioeCccfQ8s2kq+YorWWd/fab8qKkaakhzjZApH5tABQ1vPQi2ApXabnQy36i8TFCfYHAdW0l/kv7j6C+k8bWo54AkgRAq0gssQEJHbPBrYBKcWg9LqdGS0aWoKDNSoNn+6pjiadn35cOW1V21S6UY0W0RBy1HpZmisiGSrd8eIbslmWxG2NH1xxRwyVIcwSNPsaFh3qOtyfLNc7VpC/qG65FG2/B8LZAChyWfBz14ylAJUF7LRJRa5NWgn8WDWSHV7HRao4S6cXFo8Uf4ZAC1FtgEHuMLF9XZD2SYHZhtN9Rt/BHTiyroCwxdCQdAztTn103ClS3jP9QdaTET2xndfumagZVB5GZRYuIRXEEfLUEg3bXB1DdRkJq1d07yyiF2VSJ5C0ZY7SY=
  file: _dist/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: softleader/helm-run
